"""Authority-source manifest validation for production answers.

The chatbot can run without a live URA feed in development, but production
deployments must prove that static fiscal rates and policy artifacts came
from a recent, hash-checked authority bundle. This module deliberately does
not scrape or invent URA data; it validates a manifest generated by the
release/data pipeline and reports fail-closed status when it is missing,
stale, or tampered with.
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import os
from pathlib import Path
from typing import Any

from ._root import PROJECT_ROOT

DEFAULT_AUTHORITY_MANIFEST = PROJECT_ROOT / "artifacts" / "authority" / "manifest.json"


def authority_required() -> bool:
    """Return whether stale/missing authority data should fail closed."""
    default = "true" if os.getenv("APP_ENV", "development").lower() == "production" else "false"
    return os.getenv("REQUIRE_FRESH_AUTHORITY", default).lower() in ("1", "true", "yes", "on")


def _manifest_path() -> Path:
    raw = os.getenv("URA_AUTHORITY_MANIFEST", str(DEFAULT_AUTHORITY_MANIFEST))
    return Path(raw).expanduser().resolve()


def _parse_ts(value: object) -> _dt.datetime | None:
    if not isinstance(value, str) or not value.strip():
        return None
    text = value.strip()
    if text.endswith("Z"):
        text = f"{text[:-1]}+00:00"
    try:
        parsed = _dt.datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=_dt.timezone.utc)
    return parsed.astimezone(_dt.timezone.utc)


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def get_authority_status() -> dict[str, Any]:
    """Validate and summarize the configured authority manifest."""
    path = _manifest_path()
    status: dict[str, Any] = {
        "ok": False,
        "configured": path.exists(),
        "fresh": False,
        "manifest_path": str(path),
        "version": "",
        "generated_at": "",
        "age_days": None,
        "max_age_days": None,
        "sources_checked": 0,
        "invalid_sources": [],
        "errors": [],
    }

    if not path.exists():
        status["errors"].append("authority manifest not found")
        return status

    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:  # noqa: BLE001 - status object carries the failure
        status["errors"].append(f"invalid authority manifest JSON: {type(exc).__name__}")
        return status

    status["version"] = str(manifest.get("version", ""))
    generated_at = (
        _parse_ts(manifest.get("generated_at"))
        or _parse_ts(manifest.get("updated_at"))
        or _parse_ts(manifest.get("created_at"))
    )
    status["generated_at"] = generated_at.isoformat() if generated_at else ""
    try:
        max_age_days = int(manifest.get("max_age_days", os.getenv("AUTHORITY_MAX_AGE_DAYS", "30")))
    except (TypeError, ValueError):
        max_age_days = 30
    status["max_age_days"] = max_age_days

    if generated_at is None:
        status["errors"].append("authority manifest missing generated_at timestamp")
    else:
        age_days = max(0.0, (_dt.datetime.now(_dt.timezone.utc) - generated_at).total_seconds() / 86400)
        status["age_days"] = round(age_days, 3)
        if age_days <= max_age_days:
            status["fresh"] = True
        else:
            status["errors"].append(
                f"authority manifest stale: {age_days:.1f} days old > {max_age_days} days"
            )

    sources = manifest.get("sources", [])
    if not isinstance(sources, list) or not sources:
        status["errors"].append("authority manifest has no sources")
        sources = []

    base_dir = path.parent
    for idx, source in enumerate(sources, 1):
        if not isinstance(source, dict):
            status["invalid_sources"].append({"index": idx, "error": "source entry is not an object"})
            continue
        rel_path = source.get("path") or source.get("file")
        expected_sha = str(source.get("sha256", "")).lower()
        if not rel_path:
            status["invalid_sources"].append(
                {"index": idx, "id": source.get("id", ""), "error": "source path missing"}
            )
            continue
        source_path = Path(str(rel_path))
        if not source_path.is_absolute():
            source_path = (base_dir / source_path).resolve()
        if not source_path.exists():
            status["invalid_sources"].append(
                {"index": idx, "id": source.get("id", ""), "error": "source file missing"}
            )
            continue
        status["sources_checked"] += 1
        if expected_sha and _sha256_file(source_path) != expected_sha:
            status["invalid_sources"].append(
                {"index": idx, "id": source.get("id", ""), "error": "sha256 mismatch"}
            )

    if status["invalid_sources"]:
        status["errors"].append("one or more authority source hashes failed validation")

    status["ok"] = bool(status["fresh"] and status["sources_checked"] > 0 and not status["errors"])
    return status


def require_fresh_authority() -> dict[str, Any]:
    """Return status, raising ``RuntimeError`` when freshness is mandatory."""
    status = get_authority_status()
    if authority_required() and not status["ok"]:
        errors = "; ".join(status.get("errors") or ["authority status not ok"])
        raise RuntimeError(f"fresh authority manifest required: {errors}")
    return status
