"""Build the trilingual retrieval benchmark (``evals/retrieval_multilingual``).

Every query carries the ids of the Qdrant points that answer it, so retrieval
can be scored as retrieval (Hit@1, MRR, nDCG) rather than through a generated
reply. Four sets:

``faq``       A stratified sample of the indexed FAQ rows (at most
              ``--per-file`` per source file). Each row is asked as written
              (``en_verbatim``), as a taxpayer would put it (``en_paraphrase``),
              and as that paraphrase in Luganda and Swahili, plain and
              code-switched. The gold is every point whose question is the
              same text, so a row repeated across files is not a miss.
``native``    The rows whose Luganda and Swahili questions were written into
              the corpus itself (``question_lg`` / ``question_sw``). They are
              the control for the next caveat.
``coverage``  ``Data/eval/coverage_bank.jsonl``: curated questions in all three
              languages. No point ids; the runner judges a pool of candidates.
``ood``       Questions the assistant must not answer from the corpus, in all
              three languages: general knowledge, other countries' tax, other
              Ugandan agencies, chit-chat.

Each query row names its ``parent``; the answer to it is stored once, in
``gold.jsonl``. Typo and transcript-style copies are not stored:
``eval_retrieval_multilingual.load_queries`` derives them from the paraphrase,
translated and native rows with seeded functions, the same copies on every
load.

**Caveat on the faq set.** Its paraphrases and translations are produced by
Sunflower, the model the production pivot also translates with. A Sunflower
English-to-Luganda-to-English round trip recovers Sunflower's own English
more easily than a person's Luganda, so the translate leg is flattered there.
The ``native`` and ``coverage`` sets are not generated by this script; compare
against them before trusting a faq-set number for Luganda or Swahili.

Every generated query is kept only if it is in the language it claims to be:
``app.query.detect_language`` and the receptionist's word lists
(``lexical_hits``) must both agree. The detector alone accepts a sentence that
opens in Swahili and continues in Luganda, which the first build produced.
Sunflower also translated the prompt's own instruction instead of the question
when the question followed the instruction unlabelled, so the text is labelled
(``English: …`` / ``Luganda:``), the shape ``llm.translate_text`` uses.

Run it inside ``app-api:gpu`` (for the detector) against the GPU stack:

    docker run --rm --network host --user "$(id -u):$(id -g)" -e HOME=/tmp \\
        -e APP_ENV=development -v "$PWD:/src" -w /src \\
        --entrypoint python app-api:gpu scripts/build_retrieval_multilingual_set.py

Generation is greedy, so a rerun over the same index reproduces the file.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
# The repo root too: detect_language imports ml.scripts.lang_id, and without it
# falls back to a character heuristic that mis-detects Ugandan languages.
sys.path[:0] = [str(ROOT / "App" / "backend"), str(ROOT)]
from app.query import detect_language  # noqa: E402
from app.receptionist.language import lexical_hits  # noqa: E402
from eval_retrieval_multilingual import stable_rank  # noqa: E402  (this directory)

OUT = ROOT / "evals" / "retrieval_multilingual" / "queries.jsonl"
COVERAGE_BANK = ROOT / "Data" / "eval" / "coverage_bank.jsonl"

LANG_NAME = {"lg": "Luganda", "sw": "Swahili"}

# Sunflower's documented persona, for translation only. Under it the model
# answered an English paraphrase request in Luganda, so paraphrasing uses a
# plain English-only system prompt instead.
SUNFLOWER_SYSTEM = (
    "You are Sunflower, a multilingual assistant made by Sunbird AI who understands "
    "all Ugandan languages. You specialise in accurate translations, explanations, "
    "summaries and other cross-lingual tasks."
)
ENGLISH_SYSTEM = "You are a careful English editor. You always reply in English."

PARAPHRASE_PROMPTS = (
    "Paraphrase the English question below in plain everyday English, the way an "
    "ordinary Ugandan taxpayer would type it to a help-desk chatbot. Keep the meaning. "
    "Avoid the official wording and rare technical terms where an everyday word "
    "exists; common acronyms (URA, TIN, VAT, PAYE, EFRIS) are fine. If the question "
    "relies on a topic it does not name, name it (topic: {topic}). Do not answer it."
    "\n\nOriginal question: {question}\nParaphrased question:",
    "Reword this question in simple English as a member of the public would ask it. "
    "Same meaning, different words; mention the topic ({topic}) if the question "
    "leaves it out. Write only the reworded question in English."
    "\n\nQuestion: {question}\nReworded question:",
)

TRANSLATE_PROMPTS = (
    "Translate the following English text into {language}. It is a question — "
    "translate the question itself, do not answer it.\n\nEnglish: {text}\n{language}:",
    "Translate into {language}. Write only the {language} question.\n\nEnglish: {text}\n{language}:",
)

CODESWITCH_PROMPTS = (
    "Translate the following English question into everyday spoken {language}, as "
    "people in Uganda say it, keeping the English words for tax terms where people "
    "normally would. Translate the question itself, do not answer it."
    "\n\nEnglish: {text}\n{language} (spoken):",
)

_LEAK = re.compile(
    r"translat|tafsiri|kivvuunul|vvuunul|swali lenyewe|do not answer|usilijibu|tokyaddamu|tokiddamu|"
    r"reply with|paraphras|reworded",
    re.I,
)
_LOOP = re.compile(r"\b(\w+)(?:\W+\1\b){3,}", re.I)

# Out-of-domain probes. Categories, not phrasing tricks: each is something a
# member of the public plausibly asks a URA assistant and must not get an
# answer to from the URA corpus.
OOD_EN: list[tuple[str, str]] = [
    ("general", "What is the capital city of France?"),
    ("general", "Who won the 2022 football World Cup?"),
    ("general", "How do I cook matooke with groundnut sauce?"),
    ("general", "What is photosynthesis?"),
    ("general", "How far is the moon from the earth?"),
    ("general", "Which smartphone has the best camera this year?"),
    ("general", "What are the symptoms of malaria?"),
    ("general", "Will it rain in Kampala tomorrow?"),
    ("general", "Write me a short poem about the rain."),
    ("general", "How many players are in a netball team?"),
    ("foreign_tax", "How do I file my KRA iTax return in Kenya?"),
    ("foreign_tax", "How do I get a KRA PIN certificate?"),
    ("foreign_tax", "What is the VAT rate charged by TRA in Tanzania?"),
    ("foreign_tax", "When is the IRS income tax filing deadline in the United States?"),
    ("foreign_tax", "How do I pay council tax in the United Kingdom?"),
    ("foreign_tax", "What is the PAYE threshold set by the Rwanda Revenue Authority?"),
    ("foreign_tax", "How do I claim a GST refund in India?"),
    ("foreign_tax", "How do I register for a tax number with FIRS in Nigeria?"),
    ("other_agency", "How do I apply for a Ugandan passport?"),
    ("other_agency", "How do I register a marriage in Uganda?"),
    ("other_agency", "How do I get a certificate of good conduct from Interpol in Kampala?"),
    ("other_agency", "How do I apply for a UNEB exam re-mark?"),
    ("other_agency", "How do I join the Uganda People's Defence Forces?"),
    ("other_agency", "How do I get a birth certificate for my baby in Uganda?"),
    ("other_agency", "How do I apply for a government student loan for university?"),
    ("other_agency", "How do I report a power outage to UMEME?"),
    ("chitchat", "Hello, how are you today?"),
    ("chitchat", "Tell me a joke."),
    ("chitchat", "What is your name?"),
    ("chitchat", "I love watching football on weekends."),
    ("chitchat", "Okay, thank you very much."),
    ("chitchat", "Can you sing a song for me?"),
]

def _post(url: str, body: dict[str, Any], timeout: float = 120.0) -> dict[str, Any]:
    req = urllib.request.Request(url, data=json.dumps(body).encode(), headers={"content-type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return json.load(resp)


def norm_question(text: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"[^\w\s]", " ", (text or "").casefold())).strip()


def load_faq_points(qdrant: str, collection: str) -> list[dict[str, Any]]:
    url = f"{qdrant}/collections/{collection}/points/scroll"
    fields = ["source", "question", "answer", "tag", "row_number", "doc_type", "question_lg", "question_sw"]
    points: list[dict[str, Any]] = []
    offset = None
    while True:
        body: dict[str, Any] = {"limit": 1000, "with_payload": fields, "with_vector": False}
        if offset is not None:
            body["offset"] = offset
        page = _post(url, body)["result"]
        for p in page["points"]:
            pl = p.get("payload") or {}
            if str(pl.get("source", "")).endswith("_faqs.csv") and pl.get("question") and pl.get("answer"):
                points.append({"id": str(p["id"]), **pl})
        offset = page.get("next_page_offset")
        if not offset:
            return points


def chat(llm: str, model: str, system: str, user: str, *, max_tokens: int = 200) -> str:
    body = {
        "model": model,
        "messages": [{"role": "system", "content": system}, {"role": "user", "content": user}],
        "temperature": 0.0,
        "max_tokens": max_tokens,
    }
    for attempt in range(3):
        try:
            out = _post(f"{llm}/chat/completions", body)
            text = out["choices"][0]["message"]["content"] or ""
            return clean_generation(text)
        except Exception:  # noqa: BLE001 — retried, then surfaced as empty
            time.sleep(2 * (attempt + 1))
    return ""


def clean_generation(text: str) -> str:
    text = re.sub(r"<think>.*?</think>", "", text, flags=re.S).strip()
    first = next((line.strip() for line in text.splitlines() if line.strip()), "")
    first = re.sub(r"^(question|translation|rewritten question|answer)\s*:\s*", "", first, flags=re.I)
    return first.strip().strip('"').strip("“”").strip()


def plausible(source: str, generated: str) -> bool:
    """Rejects empty output, an answer instead of a question, or a runaway."""
    if not generated or _LEAK.search(generated) or _LOOP.search(generated):
        return False
    ratio = len(generated) / max(1, len(source))
    return 0.35 <= ratio <= 3.0 and len(generated) <= 400


def in_language(text: str, lang: str) -> bool:
    """The detector and the word lists both put *text* in *lang*."""
    if detect_language(text) != lang:
        return False
    hits = lexical_hits(text)
    if lang == "en":
        return hits["en"] >= 2 and hits["lg"] == 0 and hits["sw"] == 0
    other = "sw" if lang == "lg" else "lg"
    return hits[lang] >= 1 and hits[lang] > hits[other]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--qdrant", default="http://127.0.0.1:6333")
    ap.add_argument("--collection", default="ura_knowledge_base_jsonl_active")
    ap.add_argument("--llm", default="http://127.0.0.1:8011/v1")
    ap.add_argument("--model", default="Sunbird/Sunflower-14B-FP8")
    ap.add_argument("--per-file", type=int, default=3)
    ap.add_argument("--workers", type=int, default=16)
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args()

    points = load_faq_points(args.qdrant, args.collection)
    gold_by_question: dict[str, list[str]] = {}
    for p in points:
        gold_by_question.setdefault(norm_question(p["question"]), []).append(p["id"])
    print(f"faq points {len(points)}; distinct questions {len(gold_by_question)}", file=sys.stderr)

    by_file: dict[str, list[dict[str, Any]]] = {}
    for p in points:
        by_file.setdefault(p["source"], []).append(p)
    sample: list[dict[str, Any]] = []
    for source in sorted(by_file):
        seen: set[str] = set()
        for p in sorted(by_file[source], key=lambda r: stable_rank(r["id"])):
            key = norm_question(p["question"])
            if key in seen or len(key.split()) < 3:
                continue
            seen.add(key)
            sample.append(p)
            if len(seen) >= args.per_file:
                break
    print(f"sampled {len(sample)} rows from {len(by_file)} files", file=sys.stderr)

    rejected: list[str] = []

    def generate(task: tuple[str, str, str, tuple[str, ...], dict[str, str], str]) -> tuple[str, str]:
        """First prompt whose output is plausible and in *lang*; "" when none is."""
        key, system, lang, prompts, fields, source = task
        last = ""
        for prompt in prompts:
            out = chat(args.llm, args.model, system, prompt.format(**fields))
            last = out
            if plausible(source, out) and in_language(out, lang) and out.casefold() != source.casefold():
                return key, out
        rejected.append(f"{key}: {last[:90]!r}")
        return key, ""

    def run(tasks: list[tuple[str, str, str, tuple[str, ...], dict[str, str], str]]) -> dict[str, str]:
        with ThreadPoolExecutor(max_workers=args.workers) as pool:
            return dict(pool.map(generate, tasks))

    para = run([
        (p["id"], ENGLISH_SYSTEM, "en", PARAPHRASE_PROMPTS,
         {"topic": str(p.get("tag") or "tax").replace("_", " "), "question": p["question"]}, p["question"])
        for p in sample
    ])
    rows: list[dict[str, Any]] = []
    english = {p["id"]: para.get(p["id"]) or p["question"] for p in sample}

    tasks: list[tuple[str, str, str, tuple[str, ...], dict[str, str], str]] = []
    for p in sample:
        text = english[p["id"]]
        for lang, name in LANG_NAME.items():
            fields = {"language": name, "text": text}
            tasks.append((f"{p['id']}|{lang}|mt", SUNFLOWER_SYSTEM, lang, TRANSLATE_PROMPTS, fields, text))
            tasks.append((f"{p['id']}|{lang}|cs", SUNFLOWER_SYSTEM, lang, CODESWITCH_PROMPTS, fields, text))
    for i, (_, question) in enumerate(OOD_EN):
        for lang, name in LANG_NAME.items():
            tasks.append((f"ood{i}|{lang}|mt", SUNFLOWER_SYSTEM, lang, TRANSLATE_PROMPTS,
                          {"language": name, "text": question}, question))
    generated = run(tasks)

    # The answer to each question lives once, in gold.jsonl, keyed by parent.
    gold: dict[str, dict[str, Any]] = {}
    for p in sample:
        gold[p["id"]] = {
            "parent": p["id"], "gold_ids": gold_by_question[norm_question(p["question"])],
            "gold_question": p["question"], "gold_answer": p["answer"], "source": p["source"], "tag": p.get("tag", ""),
        }
        rows.append({"set": "faq", "parent": p["id"], "id": f"{p['id']}:en_verbatim", "lang": "en",
                     "variant": "verbatim", "query": p["question"], "generator": "corpus"})
        if english[p["id"]] != p["question"]:
            rows.append({"set": "faq", "parent": p["id"], "id": f"{p['id']}:en_paraphrase", "lang": "en",
                         "variant": "paraphrase", "query": english[p["id"]], "generator": "sunflower-14b"})
        for lang in LANG_NAME:
            for kind, variant in (("mt", "translation"), ("cs", "codeswitch")):
                text = generated.get(f"{p['id']}|{lang}|{kind}", "")
                if text:
                    rows.append({"set": "faq", "parent": p["id"], "id": f"{p['id']}:{lang}_{variant}", "lang": lang,
                                 "variant": variant, "query": text, "generator": "sunflower-14b"})

    for p in points:
        for lang in LANG_NAME:
            native = str(p.get(f"question_{lang}") or "").strip()
            if not native:
                continue
            gold.setdefault(p["id"], {
                "parent": p["id"], "gold_ids": gold_by_question[norm_question(p["question"])],
                "gold_question": p["question"], "gold_answer": p["answer"], "source": p["source"],
                "tag": p.get("tag", ""),
            })
            rows.append({"set": "native", "id": f"{p['id']}:{lang}_native", "parent": p["id"], "lang": lang,
                         "variant": "native", "query": native, "generator": "corpus"})

    for line in COVERAGE_BANK.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        item = json.loads(line)
        parent = f"cov:{item['id']}"
        for lang, question in (item.get("question") or {}).items():
            if lang in ("en", "lg", "sw") and question:
                gold.setdefault(parent, {
                    "parent": parent, "gold_ids": [], "gold_question": item["question"].get("en", ""),
                    "expect_any": item.get("expect_any", []), "domain": item.get("domain", ""),
                })
                rows.append({"set": "coverage", "id": f"{parent}:{lang}", "parent": parent, "lang": lang,
                             "variant": "curated", "query": question, "generator": "coverage_bank"})

    for i, (category, question) in enumerate(OOD_EN):
        gold[f"ood{i}"] = {"parent": f"ood{i}", "gold_ids": []}
        rows.append({"set": "ood", "id": f"ood{i}:en", "parent": f"ood{i}", "lang": "en", "variant": category,
                     "query": question, "generator": "hand"})
        for lang in LANG_NAME:
            text = generated.get(f"ood{i}|{lang}|mt", "")
            if text:
                rows.append({"set": "ood", "id": f"ood{i}:{lang}", "parent": f"ood{i}", "lang": lang,
                             "variant": category, "query": text, "generator": "sunflower-14b"})

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows), encoding="utf-8")
    out.with_name("gold.jsonl").write_text(
        "".join(json.dumps(g, ensure_ascii=False) + "\n" for g in gold.values()), encoding="utf-8")
    counts: dict[str, int] = {}
    for row in rows:
        key = f"{row['set']}/{row['lang']}"
        counts[key] = counts.get(key, 0) + 1
    print(json.dumps({"rows": len(rows), "by_set_lang": counts, "rejected": len(rejected)}, indent=1), file=sys.stderr)
    for line in rejected:
        print("  rejected:", line, file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
