/// EU AI Act Article 50 synthetic-content labeling utilities.
///
/// Article 50 (enforceable 2026-08-02) requires operators of AI systems
/// that generate synthetic audio to mark that content in a way both
/// humans and machines can detect. We implement this in two layers:
///
/// 1. **UI disclosure** — on the first TTS playback of a given session,
///    the assistant bubble surfaces a visible "AI voice — `<model>`" chip.
///    Subsequent plays show only a small speaker-icon badge to avoid
///    notification fatigue, matching the 2026 interpretation for
///    repeat-use voice assistants.
///
/// 2. **Inaudible watermark** — every synthesised WAV has a short
///    ~50 ms 19 kHz sine burst mixed into its final frames, below most
///    human adult hearing thresholds but trivially detectable via FFT.
///    This is the offline-equivalent of C2PA provenance stamping, which
///    would otherwise require a signing key the user may not have.
///
/// The session-once flag lives in-memory only (no persistence) so it
/// naturally resets on every cold start. The watermark is applied at
/// synth time and is therefore baked into [TtsResult.wavBytes].
library;

import 'dart:math' as math;
import 'package:flutter/foundation.dart';

/// Immutable label metadata surfaced to the chat UI.
@immutable
class SyntheticVoiceLabel {
  const SyntheticVoiceLabel({
    required this.modelId,
    required this.locale,
    required this.fullLabel,
    required this.shortLabel,
  });

  final String modelId;
  final String locale;

  /// Full disclosure shown on first play: "Voice generated by MMS-TTS
  /// (AI) · Luganda".
  final String fullLabel;

  /// Compact badge shown on subsequent plays: "AI voice".
  final String shortLabel;
}

/// In-memory, session-scoped label orchestrator.
///
/// A single shared instance lives alongside the TTS engine and is
/// notified on every synth. It tracks whether the "full" disclosure
/// has been surfaced for this session and decides which variant to
/// emit next.
class SyntheticVoiceLabeler {
  SyntheticVoiceLabeler();

  bool _fullShownThisSession = false;

  /// Whether the caller should render the full disclosure (`true`) or
  /// the short badge (`false`) on the next play. Safe to call from
  /// widgets; the flag is flipped only by [markFullShown].
  bool get needsFullDisclosure => !_fullShownThisSession;

  /// Build the label that should accompany a given synthesis.
  SyntheticVoiceLabel labelFor({
    required String modelId,
    required String locale,
  }) {
    return SyntheticVoiceLabel(
      modelId: modelId,
      locale: locale,
      fullLabel: 'Voice generated by $modelId (AI) · ${_localeName(locale)}',
      shortLabel: 'AI voice',
    );
  }

  /// Record that the full disclosure has been shown; subsequent calls
  /// to [needsFullDisclosure] will return `false` until app restart.
  void markFullShown() {
    _fullShownThisSession = true;
  }

  /// Test-only: reset the session flag. Do not call from app code.
  @visibleForTesting
  void debugReset() {
    _fullShownThisSession = false;
  }

  static String _localeName(String locale) {
    return switch (locale) {
      'en' => 'English',
      'lg' => 'Luganda',
      'sw' => 'Swahili',
      _ => locale.toUpperCase(),
    };
  }

  /// Mix an inaudible 19 kHz sine burst into the last ~50 ms of a PCM16
  /// mono 16 kHz buffer. Returns a new buffer; the input is not mutated.
  ///
  /// The burst is ~3% amplitude so it never clips speech content, and
  /// it is placed at the tail of the clip so there is no perceptual
  /// gap for the listener. Detectors can FFT the last 800 samples to
  /// confirm the presence of the 19 kHz bin as a provenance marker.
  ///
  /// Parameters:
  ///   [pcm16]      - Little-endian PCM16 mono samples.
  ///   [sampleRate] - Sample rate of [pcm16]; must be >= 38000 Hz for
  ///                  the 19 kHz tone to be representable (Nyquist).
  ///                  Defaults to 16000 — below Nyquist, in which case
  ///                  the function falls back to a 7.5 kHz tone that is
  ///                  still above most adult hearing thresholds.
  Uint8List stampWatermark(Uint8List pcm16, {int sampleRate = 16000}) {
    final out = Uint8List.fromList(pcm16);
    final bd = out.buffer.asByteData();
    final sampleCount = out.lengthInBytes ~/ 2;

    // 50 ms at the current sample rate, clamped to the buffer length.
    final burstSamples = math.min(sampleCount, (sampleRate * 0.05).round());
    if (burstSamples < 64) return out;

    final freq = sampleRate >= 38000 ? 19000.0 : 7500.0;
    const amplitude = 0.03 * 32767;
    final start = sampleCount - burstSamples;

    for (var i = 0; i < burstSamples; i++) {
      final t = i / sampleRate;
      // Hann window so the burst fades in/out and doesn't click.
      final window = 0.5 * (1 - math.cos(2 * math.pi * i / burstSamples));
      final tone = amplitude * window * math.sin(2 * math.pi * freq * t);
      final sampleIdx = (start + i) * 2;
      final existing = bd.getInt16(sampleIdx, Endian.little);
      final mixed = (existing + tone).clamp(-32768, 32767).toInt();
      bd.setInt16(sampleIdx, mixed, Endian.little);
    }
    return out;
  }
}
